apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  ports:
    - port: 80
  selector:
    app: php
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: php
        tier: frontend
    spec:
      containers:
      - image: php:6.2.1-apache
        name: php
        env:
        - name: php_DB_HOST
          value: php-mysql
        - name: php_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: php_DB_USER
          value: php
        ports:
        - containerPort: 80
          name: php
        volumeMounts:
        - name: php-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: php-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
